### ISSUE TITLE
How to pass server address and database

### ISSUE THREAD

**Issue by noah0341** [ahmet/osin-rethinkdb#3]
Not sure if a documentation issue or not implemented, but I cannot figure out how to properly load this storage driver in osin and pass the server address and database name to it.

**Comment by ahmet** [comment]
It's lack of documentation and sorry about that.

You can import gorethink like:
```golang
import r "gopkg.in/dancannon/gorethink.v1"
```


Then initialize osin with NewServer like:
```golang
session, err := r.Connect(r.ConnectOpts{
    Address:  "localhost:28015",
    Database: "osin_rethinkdb_storage"})
if err != nil {
    panic(err)
}
storage := RethinkDBStorage.New(session)
server := osin.NewServer(osin.NewServerConfig(), storage)
```

**Comment by noah0341** [comment]
That worked great, thanks!
